# Generated by Django 2.0.3 on 2018-05-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('arquivo_video', models.FileField(upload_to='videos')),
                ('postado', models.BooleanField(default=False)),
                ('glossario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glossario.Glossario')),
            ],
        ),
    ]
