# Generated by Django 2.0.5 on 2018-05-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossario',
            name='pai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Glossario.Glossario'),
            preserve_default=False,
        ),
    ]
