# Generated by Django 2.0.3 on 2018-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0002_auto_20180413_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinal',
            name='arquivo_video',
            field=models.FileField(blank=True, upload_to='Glossario/videos'),
        ),
    ]
