# Generated by Django 2.0.3 on 2018-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0003_sinal_arquivo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='arquivo_video',
            field=models.FileField(default=False, upload_to='static/Glossario/videos'),
        ),
    ]
