# Generated by Django 2.0.5 on 2018-05-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0003_auto_20180508_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='pai',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Glossario.Glossario'),
        ),
    ]
