# Generated by Django 2.0.5 on 2018-06-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0004_auto_20180528_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='universidade',
        ),
    ]
