# Generated by Django 2.0.5 on 2018-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0005_auto_20180604_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='curso',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='universidade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
