# Generated by Django 2.0.5 on 2018-05-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0005_auto_20180508_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossario',
            name='pai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Glossario.Glossario'),
        ),
    ]
