# Generated by Django 2.0.3 on 2018-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0006_auto_20180416_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='arquivo_video',
            field=models.FileField(blank=True, upload_to='Glossario/static/Glossario/videos'),
        ),
    ]
