# Generated by Django 2.0.5 on 2018-05-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0006_auto_20180508_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glossario.Tema')),
            ],
        ),
        migrations.AddField(
            model_name='sinal',
            name='temas',
            field=models.ManyToManyField(to='Glossario.Tema'),
        ),
    ]
