# Generated by Django 2.0.5 on 2018-05-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0007_auto_20180523_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='pai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Glossario.Tema'),
        ),
    ]
