# Generated by Django 2.0.5 on 2018-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0007_auto_20180605_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='membro',
            field=models.ManyToManyField(related_name='membro', to='Glossario.Glossario'),
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='perfil',
            name='responsavel',
            field=models.ManyToManyField(related_name='responsavel', to='Glossario.Glossario'),
        ),
    ]
