# Generated by Django 2.0.3 on 2018-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0008_auto_20180416_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='postado',
            field=models.BooleanField(),
        ),
    ]
