# Generated by Django 2.0.4 on 2018-06-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0009_auto_20180607_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='glossarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='membro', to='Glossario.Glossario'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='glossarios_responsavel',
            field=models.ManyToManyField(blank=True, null=True, related_name='responsavel', to='Glossario.Glossario'),
        ),
    ]
