# Generated by Django 2.0.3 on 2018-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0009_auto_20180416_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='arquivo_video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
