# Generated by Django 2.0.5 on 2018-05-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0001_initial'),
        ('Glossario', '0010_auto_20180523_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinal',
            name='responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Perfil.Perfil'),
        ),
    ]
