# Generated by Django 2.0.5 on 2018-06-14 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0010_auto_20180611_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinal',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='sinal',
            name='postador',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Glossario.Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='glossarios',
            field=models.ManyToManyField(blank=True, related_name='membro', to='Glossario.Glossario'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='glossarios_responsavel',
            field=models.ManyToManyField(blank=True, related_name='responsavel', to='Glossario.Glossario'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
