# Generated by Django 2.0.5 on 2018-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0011_auto_20180614_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinal',
            old_name='arquivo_video',
            new_name='sinal_video',
        ),
        migrations.AddField(
            model_name='sinal',
            name='conceito_video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='sinal',
            name='temas',
            field=models.ManyToManyField(blank=True, to='Glossario.Tema'),
        ),
    ]
