# Generated by Django 2.0.5 on 2018-05-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0012_auto_20180525_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='responsavel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Perfil.Perfil'),
        ),
    ]
