# Generated by Django 2.0.5 on 2018-05-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glossario', '0013_auto_20180525_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinal',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Perfil.Perfil'),
        ),
    ]
